{{- if .Values.reminderService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-reminder-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: reminder-service
spec:
  type: {{ .Values.reminderService.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.reminderService.service.port | default 8001 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: reminder-service
{{- end }}
