"""
Data models for hackathon-todo application.

This module defines the Task dataclass representing a single todo item
with validation logic for title constraints.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Task:
    """
    Represents a single todo item.

    Attributes:
        id: Unique identifier (auto-generated by storage)
        title: Brief task description (required, non-empty)
        description: Detailed task information (optional, default: "")
        completed: Completion status (default: False)
        created_at: Creation timestamp (auto-generated)

    Raises:
        ValueError: If title is empty or whitespace-only

    Examples:
        >>> task = Task(id=1, title="Buy groceries", description="Milk, eggs")
        >>> task.title
        'Buy groceries'
        >>> task.completed
        False
    """

    id: int
    title: str
    description: str = ""
    completed: bool = False
    created_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self) -> None:
        """
        Validate and normalize task attributes after initialization.

        Ensures title is non-empty and strips whitespace from title and description.

        Raises:
            ValueError: If title is empty or contains only whitespace
        """
        if not self.title or not self.title.strip():
            raise ValueError("Task title cannot be empty")

        # Normalize title and description by stripping whitespace
        self.title = self.title.strip()
        self.description = self.description.strip()

    def toggle_completed(self) -> None:
        """
        Toggle the completion status of the task.

        Changes completed from True to False or False to True.

        Examples:
            >>> task = Task(id=1, title="Test")
            >>> task.completed
            False
            >>> task.toggle_completed()
            >>> task.completed
            True
        """
        self.completed = not self.completed

    def update(self, title: str | None = None, description: str | None = None) -> None:
        """
        Update task attributes with validation.

        Args:
            title: New title (must be non-empty if provided)
            description: New description (can be empty)

        Raises:
            ValueError: If title is empty or whitespace-only

        Examples:
            >>> task = Task(id=1, title="Original", description="Original desc")
            >>> task.update(title="Updated")
            >>> task.title
            'Updated'
            >>> task.update(description="New description")
            >>> task.description
            'New description'
        """
        if title is not None:
            if not title or not title.strip():
                raise ValueError("Task title cannot be empty")
            self.title = title.strip()

        if description is not None:
            self.description = description.strip()
